### ISSUE TITLE
Fish DNA samples not harvesting

### ISSUE THREAD

**Issue by mandrewj** [BioKIC/NEON-Biorepository-Data-Docs#78] opened 2020-10-13 22:39 UTC
Fish  DNA occurrences are not harvesting any occurrence data.  There are no locality or identification data on the records.
https://biorepo.neonscience.org/portal/collections/misc/collprofiles.php?collid=66&emode=1

**Comment by kyule** [comment] 2020-10-15 18:35
This is a partial duplicate of (https://github.com/BioKIC/NEON-Biorepository/issues/142)

**Closed by kyule** 2020-10-15 18:35 UTC
